CREATE TABLE IF NOT EXISTS usuario (

    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(45) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    ENDERECO VARCHAR(50) NOT NULL,
    DATA_NASC DATE,
    QTD_LIVROS INT,
    ESTA_DEVENDO BOOL
);