CREATE TABLE IF NOT EXISTS livro_autor(
    LIVRO_FK INT NOT NULL,
    AUTOR_FK INT NOT NULL,
    FOREIGN KEY (LIVRO_FK) REFERENCES livro(ID),
    FOREIGN KEY (AUTOR_FK) REFERENCES autor(ID),
    PRIMARY KEY (LIVRO_FK, AUTOR_FK)
);