CREATE TABLE IF NOT EXISTS edicao(
    COD INT PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL,
    EDITORA_FK INT NOT NULL,
    LIVRO_FK INT NOT NULL,
    ANO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    IDIOMA VARCHAR(50) NOT NULL,
    TOTAL_PAG INT NOT NULL,
    FOREIGN KEY (EDITORA_FK) REFERENCES editora(ID),
    FOREIGN KEY (LIVRO_FK) REFERENCES livro(ID)
);