CREATE TABLE IF NOT EXISTS edicao(
    COD INT PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL,
    EDITORA_FK INT NOT NULL,
    LIVRO_FK INT NOT NULL,
    ANO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    IDIOMA VARCHAR(50) NOT NULL,
    TOTAL_PAG INT NOT NULL
);