CREATE TABLE IF NOT EXISTS locacao(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USUARIO_FK INT NOT NULL,
    FUNCIONARIO_FK INT NOT NULL,
    EDICAO_COD INT NOT NULL,
    PRAZO DATE NOT NULL,
    DATA_LOCACAO DATE,
    ANO INT,
    ABERTA BOOL,
    FOREIGN KEY (USUARIO_FK) REFERENCES usuario(ID),
    FOREIGN KEY (FUNCIONARIO_FK) REFERENCES funcionario(ID),
    FOREIGN KEY (EDICAO_COD) REFERENCES edicao(COD)
);